# This file is completely ChatGPT because i dont want to learn YAML
name: Build and Release Eidos

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu  # Debian-based (Ubuntu)
          - x86_64-unknown-linux-gnu  # Arch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build for ${{ matrix.target }}
        run: |
          cd cargo
          cargo build --release --target=${{ matrix.target }}

      - name: Rename and prepare binary
        run: |
          BIN_NAME="eidos-${{ matrix.target }}"
          mv cargo/target/${{ matrix.target }}/release/eidos $BIN_NAME
          chmod +x $BIN_NAME

      - name: Upload binary as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: eidos-${{ matrix.target }}
          path: eidos-${{ matrix.target }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Upload binaries to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/eidos-*
